v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {WSPR Transmitter} 1290 -2390 0 0 1.5 1.5 {}
T {Features of the WSPR transmitter:
-) The FSK-4 modulation is based on an analog IQ transmitter, driven by a 30 bit iterative CORDIC. 
-) An IQ-DAC with a sample rate of 218.75kSps and a bitwidth of 10 bit, followed by a 3rd-order lowpass filter, 
is upconverted in a passive voltage-mode mixer with 25% LO, generated by a divide-by-2 circuit.
-) The resulting single-ended RF output is directly connected to an analog output of the TinyTapeout chip to drive external circuitry like lowpass filters and an amplifier.} 2350 -2100 2 0 0.5 0.5 {}
T {When _oe = 1 (default):
-) Pass signal_o to bidir_out & to pad (output mode)
-) In this case, the RISC-V outputs drive the IQ-Modulator and are connected to the corrsponding pads for debugging.
When _oe = 0:
-) Pass bidir_in (pad input) to bidir_out (input mode)
-) In this case, the pad can be used as a debugging input instead of the RISC-V outputs (e.g., for testing the IQ-Modulator without the RISC-V CPU).} 160 -2060 0 0 0.5 0.5 {}
T {Between the RISC-V CPU outputs (ds_Q_p, ds_Q_n, ds_I_p and ds_I_n) and four analog pads, there are SPDT switches, where the output is connected to the IQ-Modulator.
These switches can be controlled by the RISC-V CPU signals (I_ae and Q_ae) to select whether the RISC-V outputs or the analog pad inputs are connected to the IQ-Modulator.
When _ae = 1:
-) The SPDT switch connects the analog pad inputs to the IQ-Modulator.
-) This enables the use of external analog signals (e.g., from an AWG), which can be useful for testing the IQ-Modulator without the RISC-V CPU.
When _ae = 0 (default):
-) The SPDT switch connects the RISC-V outputs to the IQ-Modulator.
-) In this case, the RISC-V outputs drive the IQ-Modulator.} 160 -1840 0 0 0.5 0.5 {}
N 1140 -1400 1140 -1380 {lab=VDD_CORE}
N 2900 -380 2900 -360 {lab=VSS}
N 1140 -380 1140 -360 {lab=VSS}
N 2900 -1400 2900 -1380 {lab=VDD_ANA}
N 780 -1400 780 -1380 {lab=di_gpio_3}
N 720 -1400 720 -1380 {lab=di_gpio_2}
N 660 -1400 660 -1380 {lab=di_gpio_1}
N 600 -1400 600 -1380 {lab=di_gpio_0}
N 780 -380 780 -360 {lab=do_gpio_3}
N 720 -380 720 -360 {lab=do_gpio_2}
N 660 -380 660 -360 {lab=do_gpio_1}
N 600 -380 600 -360 {lab=do_gpio_0}
N 180 -540 200 -540 {lab=di_uart_rx}
N 180 -500 200 -500 {lab=do_uart_tx}
N 180 -1260 200 -1260 {lab=di_clock}
N 180 -1200 200 -1200 {lab=di_reset_n}
N 180 -1060 200 -1060 {lab=di_spi_so}
N 180 -800 200 -800 {lab=di_i2c_sda}
N 180 -760 200 -760 {lab=do_i2c_sda}
N 180 -720 200 -720 {lab=do_i2c_sda_oe}
N 180 -680 200 -680 {lab=do_i2c_scl}
N 180 -1020 200 -1020 {lab=do_spi_si}
N 180 -980 200 -980 {lab=do_spi_sclk}
N 180 -940 200 -940 {lab=do_spi_sram_ce}
N 3240 -1200 3260 -1200 {lab=voutp_I_RF}
N 3240 -1140 3260 -1140 {lab=voutn_I_RF}
N 3240 -620 3260 -620 {lab=voutn_Q_RF}
N 3240 -560 3260 -560 {lab=voutp_Q_RF}
N 2240 -980 2560 -980 {lab=do_lo_I}
N 2240 -780 2560 -780 {lab=do_lo_Q}
N 2080 -1300 2100 -1300 {lab=I_ae}
N 2080 -1060 2100 -1060 {lab=do_lo_I_oe}
N 2080 -700 2100 -700 {lab=do_lo_Q_oe}
N 2080 -500 2100 -500 {lab=do_ds_Q_oe}
N 2080 -1260 2100 -1260 {lab=do_ds_I_oe}
N 2080 -460 2100 -460 {lab=Q_ae}
N 2540 -1300 2560 -1300 {lab=I_ae}
N 2540 -1260 2560 -1260 {lab=vinp_I}
N 2540 -1120 2560 -1120 {lab=vinn_I}
N 2540 -460 2560 -460 {lab=Q_ae}
N 2540 -640 2560 -640 {lab=vinn_Q}
N 2080 -1180 2240 -1180 {lab=do_ds_I_p}
N 2240 -1220 2240 -1180 {lab=do_ds_I_p}
N 2080 -580 2240 -580 {lab=do_ds_Q_p}
N 2080 -1220 2100 -1220 {lab=di_ds_I_p}
N 2080 -1140 2100 -1140 {lab=di_ds_I_n}
N 2080 -1020 2100 -1020 {lab=di_lo_I}
N 2080 -940 2100 -940 {lab=di_lo_Ix}
N 2080 -820 2100 -820 {lab=di_lo_Qx}
N 2080 -740 2100 -740 {lab=di_lo_Q}
N 2240 -900 2560 -900 {lab=do_lo_Ix}
N 2240 -860 2560 -860 {lab=do_lo_Qx}
N 2240 -1080 2560 -1080 {lab=do_ds_I_n}
N 2240 -1100 2240 -1080 {lab=do_ds_I_n}
N 2080 -1100 2240 -1100 {lab=do_ds_I_n}
N 2240 -680 2560 -680 {lab=do_ds_Q_n}
N 2240 -680 2240 -660 {lab=do_ds_Q_n}
N 2080 -660 2240 -660 {lab=do_ds_Q_n}
N 2240 -1000 2260 -1000 {lab=do_lo_I}
N 2240 -1000 2240 -980 {lab=do_lo_I}
N 2080 -980 2240 -980 {lab=do_lo_I}
N 2240 -920 2260 -920 {lab=do_lo_Ix}
N 2240 -920 2240 -900 {lab=do_lo_Ix}
N 2080 -900 2240 -900 {lab=do_lo_Ix}
N 2240 -840 2260 -840 {lab=do_lo_Qx}
N 2240 -860 2240 -840 {lab=do_lo_Qx}
N 2080 -860 2240 -860 {lab=do_lo_Qx}
N 2240 -760 2260 -760 {lab=do_lo_Q}
N 2240 -780 2240 -760 {lab=do_lo_Q}
N 2080 -780 2240 -780 {lab=do_lo_Q}
N 2080 -620 2100 -620 {lab=di_ds_Q_n}
N 2080 -540 2100 -540 {lab=di_ds_Q_p}
N 2640 -1400 2640 -1380 {lab=analog_en}
N 2540 -500 2560 -500 {lab=vinp_Q}
N 2000 -1400 2000 -1380 {lab=analog_en}
N 2240 -540 2560 -540 {lab=do_ds_Q_p}
N 2240 -580 2240 -540 {lab=do_ds_Q_p}
N 2240 -660 2260 -660 {lab=do_ds_Q_n}
N 2240 -1100 2260 -1100 {lab=do_ds_I_n}
N 2240 -520 2260 -520 {lab=do_ds_Q_p}
N 2240 -540 2240 -520 {lab=do_ds_Q_p}
N 2240 -1220 2560 -1220 {lab=do_ds_I_p}
N 2240 -1240 2240 -1220 {lab=do_ds_I_p}
N 2240 -1240 2260 -1240 {lab=do_ds_I_p}
C {devices/iopin.sym} 1140 -1400 3 0 {name=p1 lab=VDD_CORE}
C {devices/iopin.sym} 1140 -360 1 0 {name=p3 lab=VSS}
C {devices/ipin.sym} 180 -1260 2 1 {name=p21 lab=di_clock}
C {devices/ipin.sym} 180 -1200 0 0 {name=p22 lab=di_reset_n}
C {devices/ipin.sym} 180 -1060 2 1 {name=p8 lab=di_spi_so}
C {devices/ipin.sym} 180 -800 0 0 {name=p9 lab=di_i2c_sda}
C {lab_pin.sym} 2900 -360 3 0 {name=p4 sig_type=std_logic lab=VSS}
C {title-2.sym} 0 0 0 0 {name=l1 author="Simon Dorrer" rev=1.0 lock=true}
C {devices/iopin.sym} 3260 -1200 0 0 {name=p7 lab=voutp_I_RF}
C {devices/iopin.sym} 3260 -1140 0 0 {name=p6 lab=voutn_I_RF}
C {devices/iopin.sym} 3260 -560 0 0 {name=p10 lab=voutp_Q_RF}
C {devices/iopin.sym} 3260 -620 0 0 {name=p11 lab=voutn_Q_RF}
C {devices/ipin.sym} 780 -1400 3 1 {name=p13 lab=di_gpio_3
}
C {devices/opin.sym} 780 -360 3 1 {name=p14 lab=do_gpio_3
}
C {devices/ipin.sym} 720 -1400 3 1 {name=p15 lab=di_gpio_2
}
C {devices/ipin.sym} 660 -1400 3 1 {name=p16 lab=di_gpio_1
}
C {devices/ipin.sym} 600 -1400 3 1 {name=p17 lab=di_gpio_0
}
C {devices/opin.sym} 720 -360 3 1 {name=p18 lab=do_gpio_2
}
C {devices/opin.sym} 660 -360 3 1 {name=p19 lab=do_gpio_1
}
C {devices/opin.sym} 600 -360 3 1 {name=p20 lab=do_gpio_0
}
C {devices/ipin.sym} 180 -540 0 0 {name=p23 lab=di_uart_rx
}
C {devices/opin.sym} 180 -500 2 0 {name=p24 lab=do_uart_tx
}
C {devices/opin.sym} 180 -1020 2 0 {name=p2 lab=do_spi_si
}
C {devices/opin.sym} 180 -980 2 0 {name=p12 lab=do_spi_sclk
}
C {devices/opin.sym} 180 -940 2 0 {name=p25 lab=do_spi_sram_ce
}
C {devices/opin.sym} 180 -760 2 0 {name=p26 lab=do_i2c_sda}
C {devices/opin.sym} 180 -720 2 0 {name=p27 lab=do_i2c_sda_oe
}
C {devices/opin.sym} 180 -680 2 0 {name=p28 lab=do_i2c_scl
}
C {lab_pin.sym} 2100 -1300 2 0 {name=p31 sig_type=std_logic lab=I_ae}
C {devices/opin.sym} 2100 -1060 0 0 {name=p29 lab=do_lo_I_oe
}
C {devices/opin.sym} 2100 -700 0 0 {name=p30 lab=do_lo_Q_oe
}
C {devices/opin.sym} 2100 -500 0 0 {name=p32 lab=do_ds_Q_oe
}
C {devices/opin.sym} 2100 -1260 0 0 {name=p33 lab=do_ds_I_oe
}
C {lab_pin.sym} 2100 -460 2 0 {name=p34 sig_type=std_logic lab=Q_ae}
C {lab_pin.sym} 2540 -1300 0 0 {name=p39 sig_type=std_logic lab=I_ae}
C {lab_pin.sym} 2540 -460 0 0 {name=p45 sig_type=std_logic lab=Q_ae}
C {devices/ipin.sym} 2540 -1260 2 1 {name=p47 lab=vinp_I}
C {devices/ipin.sym} 2540 -1120 2 1 {name=p48 lab=vinn_I}
C {devices/ipin.sym} 2540 -500 2 1 {name=p49 lab=vinp_Q}
C {devices/ipin.sym} 2540 -640 2 1 {name=p50 lab=vinn_Q}
C {devices/ipin.sym} 2100 -1220 0 1 {name=p51 lab=di_ds_I_p}
C {devices/ipin.sym} 2100 -1140 0 1 {name=p52 lab=di_ds_I_n}
C {devices/ipin.sym} 2100 -1020 0 1 {name=p53 lab=di_lo_I}
C {devices/ipin.sym} 2100 -940 0 1 {name=p54 lab=di_lo_Ix}
C {devices/ipin.sym} 2100 -820 0 1 {name=p55 lab=di_lo_Qx}
C {devices/ipin.sym} 2100 -740 0 1 {name=p56 lab=di_lo_Q}
C {devices/opin.sym} 2260 -1100 0 0 {name=p57 lab=do_ds_I_n
}
C {devices/opin.sym} 2260 -1240 0 0 {name=p58 lab=do_ds_I_p
}
C {devices/opin.sym} 2260 -520 0 0 {name=p59 lab=do_ds_Q_p
}
C {devices/opin.sym} 2260 -660 0 0 {name=p60 lab=do_ds_Q_n
}
C {devices/opin.sym} 2260 -1000 0 0 {name=p61 lab=do_lo_I
}
C {devices/opin.sym} 2260 -920 0 0 {name=p62 lab=do_lo_Ix
}
C {devices/opin.sym} 2260 -840 0 0 {name=p63 lab=do_lo_Qx
}
C {devices/opin.sym} 2260 -760 0 0 {name=p64 lab=do_lo_Q
}
C {devices/ipin.sym} 2100 -620 0 1 {name=p65 lab=di_ds_Q_n}
C {devices/ipin.sym} 2100 -540 0 1 {name=p66 lab=di_ds_Q_p}
C {riscv_top.sym} 1140 -880 0 0 {name=x1}
C {iqmod_top.sym} 2900 -880 0 0 {name=x2}
C {lab_pin.sym} 2000 -1400 1 0 {name=p67 sig_type=std_logic lab=analog_en}
C {lab_pin.sym} 2640 -1400 1 0 {name=p68 sig_type=std_logic lab=analog_en}
C {devices/iopin.sym} 2900 -1400 3 0 {name=p69 lab=VDD_ANA}
