v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
T {WSPR Transmitter} 890 -1720 0 0 1.5 1.5 {}
T {Features of the WSPR transmitter:
-) The FSK-4 modulation is based on an analog IQ transmitter, driven by a 30 bit iterative CORDIC. 
-) An IQ-DAC with a sample rate of 218.75kSps and a bitwidth of 10 bit, followed by a 3rd-order lowpass filter, 
is upconverted in a passive voltage-mode mixer with 25% LO, generated by a divide-by-2 circuit.
-) The resulting single-ended RF output is directly connected to an analog output of the TinyTapeout chip to drive external circuitry like lowpass filters and an amplifier.} 2360 -1410 2 0 0.5 0.5 {}
N 840 -1280 840 -1260 {lab=VDD}
N 140 -1200 180 -1200 {lab=di_clock}
N 140 -1120 180 -1120 {lab=di_reset_n}
N 140 -820 180 -820 {lab=di_spi_cs}
N 140 -740 180 -740 {lab=di_uart_rx}
N 140 -400 180 -400 {lab=di_push_TX}
N 2320 -780 2360 -780 {lab=vout_RF}
N 2140 -1280 2140 -1260 {lab=VDD}
N 2140 -300 2140 -280 {lab=VSS}
N 840 -300 840 -280 {lab=VSS}
N 1440 -720 1540 -720 {lab=#net1}
N 1440 -660 1540 -660 {lab=#net2}
N 1440 -900 1540 -900 {lab=#net3}
N 1440 -840 1540 -840 {lab=#net4}
N 1440 -1180 1540 -1180 {lab=#net5}
N 1440 -520 1540 -520 {lab=#net6}
N 1440 -460 1540 -460 {lab=#net7}
N 1440 -1100 1540 -1100 {lab=#net8}
N 1440 -1040 1540 -1040 {lab=#net9}
N 140 -900 180 -900 {lab=di_spi_mosi}
C {devices/iopin.sym} 840 -1280 3 0 {name=p1 lab=VDD}
C {devices/opin.sym} 2360 -780 0 0 {name=p7 lab=vout_RF}
C {title-3.sym} 0 0 0 0 {name=l1 author="Simon Dorrer" rev=1.0 lock=true}
C {devices/iopin.sym} 840 -280 1 0 {name=p3 lab=VSS}
C {devices/ipin.sym} 140 -1200 2 1 {name=p21 lab=di_clock}
C {devices/ipin.sym} 140 -1120 0 0 {name=p22 lab=di_reset_n}
C {wspr_tx_digital_core.sym} 840 -780 0 0 {name=x1}
C {devices/ipin.sym} 140 -900 2 1 {name=p8 lab=di_spi_mosi}
C {devices/ipin.sym} 140 -740 0 0 {name=p9 lab=di_uart_rx}
C {devices/ipin.sym} 140 -400 0 0 {name=p12 lab=di_push_TX}
C {wspr_tx_iqmod.sym} 1920 -780 0 0 {name=x2}
C {lab_pin.sym} 2140 -1280 1 0 {name=p15 sig_type=std_logic lab=VDD}
C {lab_pin.sym} 2140 -280 3 0 {name=p4 sig_type=std_logic lab=VSS}
C {devices/ipin.sym} 140 -820 2 1 {name=p2 lab=di_spi_cs}
